name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Installing Packages 🥁
        run: yarn install

      - name: Building 🧱
        run: yarn build
        env:
          NEXT_PUBLIC_TRACKING_ID: G-8FBXBFXC10
          NEXT_PUBLIC_SERVICE_ID: service_qt4ryip
          NEXT_PUBLIC_TEMPLATE_ID: template_2ni69n8
          NEXT_PUBLIC_USER_ID: user_Do31sKneP4eYfn5n1nLTD

      - name: Exporting Bundle Files 🎪
        run: yarn export
      - run: touch ./out/.nojekyll

      - name: Deploy to Github-Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
